# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-22 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivateTokenModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=100)),
                ('is_user', models.BooleanField(default=False)),
            ],
        ),
    ]
