# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-15 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivatetokenmodel',
            name='token',
            field=models.CharField(max_length=5),
        ),
    ]
