# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-30 14:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopFileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_username', models.CharField(max_length=50)),
                ('development_file_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceTokenModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_version', models.FloatField()),
                ('device_token', models.CharField(max_length=100)),
                ('register_datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('update_datetime', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=500)),
                ('os_version', models.FloatField()),
                ('sound', models.CharField(max_length=30)),
                ('badge', models.IntegerField()),
                ('url', models.CharField(max_length=200)),
                ('json', models.CharField(max_length=150)),
                ('content_available', models.BooleanField(default=False)),
                ('is_production', models.BooleanField(default=False)),
                ('register_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='ProductFileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_username', models.CharField(max_length=50)),
                ('production_file_name', models.CharField(max_length=100)),
            ],
        ),
    ]
