# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-25 08:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0002_notificationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmodel',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
