# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-25 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0003_notificationmodel_register_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PemfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('development_file_name', models.CharField(max_length=100)),
                ('production_file_name', models.CharField(max_length=100)),
            ],
        ),
    ]
