# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-25 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0005_auto_20160925_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetokenmodel',
            name='os_version',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='notificationmodel',
            name='os_version',
            field=models.FloatField(),
        ),
    ]
