# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-05 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0006_notificationmodel_execute_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmodel',
            name='execute_datetime',
            field=models.CharField(default='2016/10/06 00:58', max_length=20),
        ),
    ]
