# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-07 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0008_auto_20161006_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmodel',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notificationmodel',
            name='execute_datetime',
            field=models.CharField(default='2016/10/07 23:14', max_length=16),
        ),
    ]
