# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-09 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0009_auto_20161007_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmodel',
            name='execute_datetime',
            field=models.CharField(default='2016/10/09 17:04', max_length=16),
        ),
    ]
