# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-28 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0010_auto_20161009_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetokenmodel',
            name='uuid',
            field=models.CharField(default=1, max_length=36),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notificationmodel',
            name='execute_datetime',
            field=models.CharField(default='2016/10/28 23:36', max_length=16),
        ),
    ]
