# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-23 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0010_auto_20161009_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmodel',
            name='content_available',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='notificationmodel',
            name='execute_datetime',
            field=models.CharField(default='2016/10/23 11:45', max_length=16),
        ),
    ]
