# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-23 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0011_auto_20161023_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmodel',
            name='content_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notificationmodel',
            name='execute_datetime',
            field=models.CharField(default='2016/10/23 12:06', max_length=16),
        ),
    ]
