# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-30 05:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0012_auto_20161023_1206'),
        ('push', '0011_auto_20161022_2050'),
        ('push', '0011_auto_20161028_2336'),
    ]

    operations = [
    ]
