# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-04 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0015_auto_20170104_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmodel',
            name='execute_datetime',
            field=models.CharField(default='2017/01/04 04:58', max_length=16),
        ),
    ]
