# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-04 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0016_auto_20170104_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='developfilemodel',
            name='application_name',
            field=models.CharField(default='application', max_length=20),
        ),
        migrations.AddField(
            model_name='devicetokenmodel',
            name='application_name',
            field=models.CharField(default='application', max_length=20),
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='application_name',
            field=models.CharField(default='application', max_length=20),
        ),
        migrations.AddField(
            model_name='productfilemodel',
            name='application_name',
            field=models.CharField(default='application', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationmodel',
            name='execute_datetime',
            field=models.CharField(default='2017/01/04 05:00', max_length=16),
        ),
    ]
