# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-02-12 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0017_auto_20170104_0500'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicationModel',
        ),
        migrations.RemoveField(
            model_name='developfilemodel',
            name='application_name',
        ),
        migrations.RemoveField(
            model_name='devicetokenmodel',
            name='application_name',
        ),
        migrations.RemoveField(
            model_name='notificationmodel',
            name='application_name',
        ),
        migrations.RemoveField(
            model_name='productfilemodel',
            name='application_name',
        ),
        migrations.AlterField(
            model_name='notificationmodel',
            name='execute_datetime',
            field=models.CharField(default='2017/02/12 17:57', max_length=16),
        ),
    ]
