# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-02-12 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0018_auto_20170212_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmodel',
            name='mutable_content',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notificationmodel',
            name='execute_datetime',
            field=models.CharField(default='2017/02/12 18:13', max_length=16),
        ),
    ]
